### ISSUE TITLE
installed it into my project via cocoa pods  (swift)

### ISSUE THREAD

**Issue by MarcSteven** [MobClub/SMSSDK-for-iOS#3]
When I installed it into my swift project and then it showed me the error....
Undefined symbols for architecture x8664: "_OBJC_CLASS$MOBFApplication", referenced from: objc-class-ref in SMS_SDK "_OBJC_CLASS$MOBFBaseService", referenced from: objc-class-ref in SMS_SDK "_OBJC_CLASS$MOBFData", referenced from: objc-class-ref in SMS_SDK "_OBJC_CLASS$MOBFDataService", referenced from: objc-class-ref in SMS_SDK "_OBJC_CLASS$MOBFDate", referenced from: objc-class-ref in SMS_SDK "_OBJC_CLASS$MOBFDevice", referenced from: objc-class-ref in SMS_SDK "_OBJC_CLASS$MOBFHttpService", referenced from: objc-class-ref in SMS_SDK "_OBJC_CLASS$MOBFJson", referenced from: objc-class-ref in SMS_SDK "_OBJC_CLASS$MOBFRSAHelper", referenced from: objc-class-ref in SMS_SDK "_OBJC_CLASS$_MOBFString", referenced from: objc-class-ref in SMS_SDK ld: symbol(s) not found for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by JinghuangLiu** [comment]
you still need to add a pod：MOBFoundation_IDFA 

发自我的 iPhone

**Comment by MarcSteven** [comment]
Did you use it in your swift project????Thank you so much,I will try...

**Comment by JinghuangLiu** [comment]
I am one of the SMSSDK Writer. SMSSDK support swift. All of our products need the support of MOBFoundation(Just as the Foundation.framework of Cocoa).

发自我的 iPhone

**Comment by MarcSteven** [comment]
Ok,great !!!Thank for your advice.Lack of related documentation  about Swift so the error appeared .It's a great library I loved in OC,but now I wanna write my project with Swift...Thank you so much.Happy weekend....

**Comment by JinghuangLiu** [comment]
Thanks for your feedback,We will deal it this weak.

发自我的 iPhone

**Comment by MarcSteven** [comment]
That's great,I ask for your stuff,he told me It does not support Swift.....It made me unbelievable .As well know Swift is more fashion than OC,it can develop faster  your application than OC,I like it....Hope everything goes well......

**Comment by JinghuangLiu** [comment]
We haven’t had a Swift version of SMSSDK ,but use Swift to develop with OC API is not a hard thing. Anyway, we will write a document about how to use Swift to develop with the OC API version.

**Comment by MarcSteven** [comment]
Yeah ，U're a great god .......
