### ISSUE TITLE
打出的ipa 包第一次安装 闪退

### ISSUE THREAD

**Issue by FisherEat** [MobClub/SMSSDK-for-iOS#4]
打出的ipa包iOS10上第一次安装出现闪退。我做了以下尝试：
1、添加Privacy - Contacts Usage Description ,在app delegate中这么设置
  //短信登录
    [SMS_SDK enableAppContactFriends:NO];
    [SMS_SDK registerApp:kMsgAppKey withSecret:kMsgAppSecret];
第一次安装还是闪退。闪退后，重新启动后，可以启动app。
2、去掉Privacy - Contacts Usage Description，但是设置   [SMS_SDK enableAppContactFriends:NO];此时程序无法启动，每次启动就闪退。
3、本人在测试机版本10.0.1 、10.0.2上均发现闪退。
4、本人直接用真机调试（不是安装包），程序不会出现闪退。
5、求联系1320681113@qq.com

**Comment by liyuansheng** [comment]
首先：设置授权方法是需要放在注册方法之后写的。
[SMS_SDK registerApp:kMsgAppKey withSecret:kMsgAppSecret];
[SMS_SDK enableAppContactFriends:NO];
然后：是需要在info.plist里面设置Privacy - Contacts Usage Description 这个key的，
